### ISSUE TITLE
[BUG] Unable to delete images from Train Menu

### ISSUE THREAD

**Issue by sacheenganatra** [skrashevich/double-take#102]
**Describe the bug**
I use Compreface and am whilst i can train and untrain images, I um unable to delete from the interface

**Version of Double Take**
1.13.11.1

**Expected behavior**
Expect the image to be deleted

**Additional context**
log:
error: TypeError: db.query is not a function
    at module.exports.delete (/double-take/api/src/controllers/storage.controller.js:145:8)
    at newFn (/double-take/api/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle [as handle_request] (/double-take/api/node_modules/express/lib/router/layer.js:95:5)
    at next (/double-take/api/node_modules/express/lib/router/route.js:144:13)
    at /double-take/api/src/middlewares/index.js:67:3
    at newFn (/double-take/api/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle [as handle_request] (/double-take/api/node_modules/express/lib/router/layer.js:95:5)
    at next (/double-take/api/node_modules/express/lib/router/route.js:144:13)
    at module.exports.jwt (/double-take/api/src/middlewares/index.js:9:14)
    at newFn (/double-take/api/node_modules/express-async-errors/index.js:16:20)

**Comment by skrashevich** [comment]
fixed in v1.13.11.3
