### ISSUE TITLE
[BUG] Error 502 in the Home Assistant proxy addon

### ISSUE THREAD

**Issue by Calimerorulez** [skrashevich/double-take#136]
Since a couple of days the following error is shown in the log:
```
}
error: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:387:5)
    at ServerResponse.setHeader (node:_http_outgoing:644:11)
    at ServerResponse.header (/double-take/api/node_modules/express/lib/response.js:794:10)
    at ServerResponse.send (/double-take/api/node_modules/express/lib/response.js:174:12)
    at ServerResponse.res.send (/double-take/api/src/middlewares/respond.js:41:18)
    at ServerResponse.json (/double-take/api/node_modules/express/lib/response.js:278:15)
    at ServerResponse.send (/double-take/api/node_modules/express/lib/response.js:162:21)
    at ServerResponse.res.send (/double-take/api/src/middlewares/respond.js:41:18)
    at /double-take/api/src/app.js:46:38
    at newFn (/double-take/api/node_modules/express-async-errors/index.js:16:20)

```

Using v1.13.11.4

**Comment by cbriddell** [comment]
Same issue this end...

23-10-14 04:05:43 error: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:387:5)
    at ServerResponse.setHeader (node:_http_outgoing:644:11)
    at ServerResponse.header (/double-take/api/node_modules/express/lib/response.js:794:10)
    at ServerResponse.send (/double-take/api/node_modules/express/lib/response.js:174:12)
    at ServerResponse.res.send (/double-take/api/src/middlewares/respond.js:41:18)
    at ServerResponse.json (/double-take/api/node_modules/express/lib/response.js:278:15)
    at ServerResponse.send (/double-take/api/node_modules/express/lib/response.js:162:21)
    at ServerResponse.res.send (/double-take/api/src/middlewares/respond.js:41:18)
    at /double-take/api/src/app.js:46:38
    at newFn (/double-take/api/node_modules/express-async-errors/index.js:16:20)

**Comment by arne182** [comment]
I am having this again
